
title = "I'm Chenxi Dang"
author = "Chenxi Dang"
#copyright = "2020-2021"
description = "Call me Chenxi"
welcomeText = "ğŸ‘‹ èŠ±å¾„ä¸æ›¾ç¼˜å®¢æ‰«ï¼Œè“¬é—¨ä»Šå§‹ä¸ºå›å¼€ã€‚"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = [
    "css/chroma-github.css",
    "css/custom.css"
  ]
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
#contactFormReCaptcha = "your-site-key-here"
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2006å¹´01æœˆ02æ—¥"
indexDateFormat = "2006å¹´01æœˆ02æ—¥"
listDateFormat = "2006å¹´01æœˆ02æ—¥"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"
# relatedPosts = true
# numberOfRelatedPosts = 3

# Full link to license
#license = "https://creativecommons.org/licenses/by/4.0/"

# disableTitleCapitalization = true

reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

# hidesidebar = true

# Sidebar/Content Ratio
contentratio = 0.65

[simpleAnalytics]
enable = true
# customurl = "https://analytics.example.com"

[plausibleAnalytics]
# domain = "example.com"
# serverURL = "https://analytics.example.com"

[umami]
# serverURL = "example.com"
# id = "94db1cb1-74f4-4a40-ad6c-962362670409"
# trackerScriptName = "mycustomscriptname.js"

## Social links
# use 'fa-brands' when brand icons, use 'fas' when standard solid icons.

[[socialIcons]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/Tech2Nova/"

[[socialIcons]]
icon = "fa-solid fa-envelope"
title = "e-mail"
url = "mailto:Dangchenxi650@163.com"

[[socialIcons]]
icon = "fa-brands fa-weixin"
title = "WeChat"
url = "https://weixin.qq.com/"

[[socialIcons]]
icon = "fa-brands fa-bilibili"
title = "Bilibili"
url = "https://www.bilibili.com/"



[mermaid]
# enable = true

