baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

# [module]
#   [[module.imports]]
#     path = "github.com/lxndrblz/anatole"
#     # 如果你想锁定某个具体版本（推荐），可以这样：
#     # path = "github.com/lxndrblz/anatole/v1.18.0"
# theme = 'anatole'
